# Generated by Django 3.0.3 on 2020-10-21 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0007_promotioncategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespromotion',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.CreateModel(
            name='Adertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=100)),
                ('specific_area', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('contact_info', models.CharField(max_length=100)),
                ('ad_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adownerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
