# Generated by Django 3.0.3 on 2020-10-21 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0009_adertising_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adertising',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salespromotion',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salespromotion',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
