# Generated by Django 3.0.3 on 2020-10-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0011_attachpromotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachpromotion',
            name='status',
        ),
    ]
