# Generated by Django 3.0.3 on 2020-10-22 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0012_remove_attachpromotion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachpromotion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adertising',
            name='contact_info',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adertising',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='attachpromotion',
            name='contact_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attachpromotion',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='salespromotion',
            name='contact_info',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salespromotion',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
