# Generated by Django 3.0.3 on 2020-10-22 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0013_auto_20201022_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachpromotion',
            name='attacher',
        ),
        migrations.AddField(
            model_name='attachpromotion',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authorprofile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
