# Generated by Django 3.0.3 on 2020-10-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0019_auto_20201029_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
