# Generated by Django 3.0.3 on 2020-10-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0021_fqa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fqa',
            name='replay',
        ),
    ]
