# Generated by Django 3.0.3 on 2020-11-01 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotion', '0023_moneyquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adertising',
            name='image2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='moneyquestion',
            name='check',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moneyquestion',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moneyquestion',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whosay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salespromotion',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OtherPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000)),
                ('phone', models.TextField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
