# Generated by Django 3.0.3 on 2020-11-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0024_auto_20201101_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adertising',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='otherpromotion',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='salespromotion',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Accepted', 'Accepted')], default='pending', max_length=100),
        ),
        migrations.CreateModel(
            name='PromotionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.IntegerField(default=0)),
                ('ip_address', models.CharField(max_length=200)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='promotion.AttachPromotion')),
            ],
        ),
    ]
