# Generated by Django 3.0.3 on 2020-11-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0025_auto_20201103_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionview',
            name='view',
        ),
    ]
