# Generated by Django 3.0.3 on 2020-11-03 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0027_auto_20201103_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionview',
            name='viewer',
        ),
        migrations.AddField(
            model_name='promotionview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotionview',
            name='ip_address',
            field=models.TextField(default=None),
        ),
    ]
